### ISSUE TITLE
Introduce new welcome screen and simplify SIP URIs across the board

### ISSUE THREAD

**Issue by ivelin** [RestComm/restcomm-ios-sdk#343]
Also, login and register with user credentials of a Restcomm account

Instead of requiring advanced SIP settings including user credentials in order for a Restcomm client to register with a server, the default behavior should be to register with Restcomm server account credentials on cloud.restcomm.com. Related to:
https://github.com/RestComm/RestComm-Core/issues/784

**Comment by atsakiridis** [comment]
@ivelin I had already opened an issue for this: #337, but in a slightly different context: use a Welcome Screen the first time a user logs in to ask for SIP credentials (user/pass). But as far as I can tell this is a bit different. So let's keep this issue to discuss the welcome screen activity and I'll dup the other issue on this one. 

Some notes:
* I assume the piece of info we want to have in this Welcome Screen is:
  * **Username**: Some ideas on it's form: Currently in iOS this is the full sip URI like `sip:bob@cloud.restcomm.com`, because ultimately this becomes a SIP address of record and I wanted the user to be able to use the features of such a SIP entity. On the other hand for Android where code was already in place when I jumped in, there is a simple user name in the form of `bob` and the SDK constructs the rest on it's own. But since we are moving towards the cloud maybe we should use a middle solution like: `bob@cloud.restcomm.com`, that is drop the `sip:` (as we do in web olympus) and in contrast to android make domain mandatory. I think this will be the most intuitive thing one would think when creating a cloud account (using the new functionality described at https://github.com/RestComm/RestComm-Core/issues/784)
  * **Password**: Pretty straight forward, no need to analyze further
  * **Domain**: This calls for some discussion. In the simple scenario where we are using cloud and DNS and everything is setup and the port is known I think this field isn't needed. We can infer it from the Username, by taking the domain part and using port 5060 and that would give us the Restcomm server address. But when testing we need to be able to setup domain as the username domain part might be different from the server address plus we might want to indicate the port we want to use. So I think the way to go could be to leave Domain out from the 'Welcome Screen' to make it as simple as possible but still allow it in *Settings*
* About the existing *Settings* screen:
  * I think we should definitely 'normalize' all our mobile SDKs to require the exact same set of data
  * Should we expose the sip aspects in the various SIP entities or not? I think to be inline with the new Welcome Screen we should drop them. If so this how our `Settings` would look:
    * **Username**: `bob@cloud.restcomm.com` (used to be `sip:bob@cloud.restcomm.com`)
    * **Password**: Usual
    * **Domain**: `cloud.restcomm.com[:5060]` (used to be `sip:cloud.restcomm.com[:5060]`)

What do you think?

**Comment by deruelle** [comment]
For Welcome Screen, I agree we should have 3 boxes, similar to Settings Screen : Username (blank by default), Password (blank by default), Domain (default to cloud.restcomm.com). 
The Domain is not critical if everyone is using cloud indeed but for people that want to change the domain to their local install and don't have an account on restcomm cloud, they will get an error if we remove that because the client won't be able to register. I would say we keep it for now and will remove it later when the cloud is public and allow or user creation from the Olympus clients directly as well.

On **Username** : agree on dropping the ```sip:``` part since we only support sip anyway as signalling protocol it's redundant and can confuse users not familiar with telecom + can lead to typos that leads to errors. So drop ```sip:``` everywhere in the UI.

**Comment by atsakiridis** [comment]
Good point on not leaving Domain out @deruelle. Yes let's have a reasonable default value.

Ok, been thinking about dropping the 'sip:' in the rest of the UI as well and it's a good idea (I think this is how web olympus works). The underlying SDK will continue to understand 'sip:' and in the future 'tel:', 'client:' and others that we have discussed in https://github.com/RestComm/restcomm-android-sdk/issues/210.

Another thing that I think would really help in the sense of usability is to not to have to add the domain part when adding a contact. It's too much to have the write down the whole `bob@cloud.restcomm.com` especially in a mobile device and its error prone. 

I think we could allow the user to just use `bob` and if they do that then add the domain internally. If the user is using registrar-less mode (and hence there's no domain being setup) we could just return an error saying that you need the full URI when in registrar-less mode

**Comment by deruelle** [comment]
on understanding sip:, tel:, client: we should use visual icons at "contact creation" to avoid messing up users with telco concepts.

Agree on removing the domain part. you shoul only be able to call from your own domain (the domain you're registered with) anyway. Registrar-less will end up disappearing too when Restcomm Cloud is public

**Comment by atsakiridis** [comment]
Ok, visual icons might be tricky, but let me think about it a bit

**Comment by ivelin** [comment]
Think about the way a user logs into gmail. 

For the default free personal accounts, only username and password are required. And now google introduced two factor phone authentication plus other options that we can leave for another discussion. 

Respectively to login into an organization account the user enters username @ domain.

This is an approach we can work with. 

PayPal for example allow mobile app users to register with either email or phone number. Also a valid method to consider for Restcomm end user accounts. 

In the most common case we should only ask for plain user and password. 

When SSO is finished, signing up and signing in should be as simple as picking an identity provider and authorizing Restcomm to access the identity. Facebook, Google, LinkedIn, Twitter, WeChat. 






Ivelin

**Comment by ivelin** [comment]
Also,

Agree that sip: should be implied. No need for the user to enter. 

Domain or Server IP should be an advanced registration and sign in option that is not required nor prominent by default.

**Comment by deruelle** [comment]
Agreed on that when the cloud is public and running but in the meanwhile I would say to keep the Domain box and only remove it when RestComm Cloud is live

**Comment by atsakiridis** [comment]
@deruelle, @ivelin to sum up, here are the impacts. Please let me know if anything is missing:

1. Add welcome screen where user will see fields username (empty), password (empty), domain (default value: cloud.restcomm.com)
2. Remove 'sip:' from all occurences in the App UI (i.e. contacts) and make SDK accept it (i.e. add the 'sip:' internally for settings and calls/messages).
3. See how we can make it easy to pick alternate schemes, like `sip:`, `tel:`, `client:` when creating a contact, with a default of `sip:`
4. Remove the need to have domain part in the Olympus contacts. The SDK should be able to figure it out by checking the **domain** Setting. If no domain is set (i.e. registrar-less mode), then when adding a contact in Olympus, domain should be added for them to work

One question though: I was thinking that after doing those changes I should also update the default contacts in Olympus App so that sip: and domain parts are removed. But if I do that and then somebody who doesn't have a cloud account and wants to demo the App they won't be able to work in registrar-less fashion with no friction as they can now (they would have to add a contact with domain). 

What do you think about that? 

Do we plan to allow for users to freely add 'trial' accounts in the cloud so that we get rid of the registrar-less option.

**Comment by deruelle** [comment]
In registrar less mode they should still fill the domain. In the end, they call a domain, by default it's cloud.restcomm.com so it will work to call +1234 as the app will automatically append the domain.
