### ISSUE TITLE
sofia-sip Library Compilation Issues

### ISSUE THREAD

**Issue by ForGuru** [RestComm/restcomm-ios-sdk#470]
Hi,

I am trying iOS SDK and stuck on Sofia-sip library. Couldn't get it compiled. Please provide some help on this.

**Comment by atsakiridis** [comment]
Hello @ForGuru, 

Can you ask your question on stack overflow, so that a larger audience can benefit from the discussion? We will answer that there. If this turns out to be an issue with the SDK, you can then open issue here.

Also notice the guide to get you started on iOS SDK: http://documentation.telestax.com/connect/sdks/restcomm-client-ios-sdk-quick-start.html

Best regards,
Antonis

**Comment by ForGuru** [comment]
Thanks for the reply. I have posted there. I appreciate the efforts for larger community 

http://stackoverflow.com/questions/39955644/sofia-sip-ua-library-compilation-for-restcomm-ios-sdk

**Comment by atsakiridis** [comment]
Thanks, answered 👍
